name: Auto Zip and Release

on:
  push:
    branches:
      - main

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create ZIP of repo contents
        run: |
          zip -r repo.zip . -x ".git/*" ".github/*" ".gitignore"

      - name: Generate unique release tag
        id: tag
        run: echo "tag=v-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "Release ${{ steps.tag.outputs.tag }}"
          files: repo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
