name: Zip and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP of repo contents
        run: |
          zip -r repo.zip . -x ".git/*" ".github/*" ".gitignore"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: repo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
